config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "charters#index"
  resources :charters do
    resources :sells, only: [:create, :destroy]
    resources :purchases, only: [:index, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charter.rb
class Charter < ApplicationRecord
  # バリデーション
  with_options presence: true do
    validates :departure
    validates :arrive
    validates :size
    validates :buy_price
    validates :prefecture_id
    validates :city
    validates :charter_address
    validates :tell_number
  end
  
  # アソシエーション
  belongs_to :user
  has_many :sells, dependent: :destroy
  has_one  :purchase, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # search
  def self.search(search)
    if search != ""
      Charter.where('arrive LIKE(?)', "%#{search}%")
    else
      Charter.all
    end
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '北海道'}, {id: 3, name: '青森県'}, {id: 4, name: '岩手県'},
    {id: 5, name: '宮城県'}, {id: 6, name: '秋田県'}, {id: 7, name: '山形県'},
    {id: 8, name: '福島県'}, {id: 9, name: '茨城県'}, {id: 10, name: '栃木県'},
    {id: 11, name: '群馬県'}, {id: 12, name: '埼玉県'}, {id: 13, name: '千葉県'},
    {id: 14, name: '東京都'}, {id: 15, name: '神奈川県'}, {id: 16, name: '新潟県'},
    {id: 17, name: '富山県'}, {id: 18, name: '石川県'}, {id: 19, name: '福井県'},
    {id: 20, name: '山梨県'}, {id: 21, name: '長野県'}, {id: 22, name: '岐阜県'},
    {id: 23, name: '静岡県'}, {id: 24, name: '愛知県'}, {id: 25, name: '三重県'},
    {id: 26, name: '滋賀県'}, {id: 27, name: '京都府'}, {id: 28, name: '大阪府'},
    {id: 29, name: '兵庫県'}, {id: 30, name: '奈良県'}, {id: 31, name: '和歌山県'},
    {id: 32, name: '鳥取県'}, {id: 33, name: '島根県'}, {id: 34, name: '岡山県'},
    {id: 35, name: '広島県'}, {id: 36, name: '山口県'}, {id: 37, name: '徳島県'},
    {id: 38, name: '香川県'}, {id: 39, name: '愛媛県'}, {id: 40, name: '高知県'},
    {id: 41, name: '福岡県'}, {id: 42, name: '佐賀県'}, {id: 43, name: '長崎県'},
    {id: 44, name: '熊本県'}, {id: 45, name: '大分県'}, {id: 46, name: '宮崎県'},
    {id: 47, name: '鹿児島県'}, {id: 48, name: '沖縄県'}
  ]

  include ActiveHash::Associations
  has_many :charters
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  belongs_to :charter
end

app/models/sell.rb
class Sell < ApplicationRecord
  # バリデーション
  validates :sell, presence: true
  validates :sell,
    numericality: { greater_than_or_equal_to: 5000, less_than_or_equal_to: 10000000 },
    format: { with: /\A[0-9]+\z/ }
  # アソシエーション
  belongs_to :user
  belongs_to :charter
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # バリデーション
  with_options presence: true do
    validates :username
    validates :email
    validates :password
    validates :phone_number
    validates :prefecture_address
    validates :city_address
    validates :house_number
  end

  validates :email, format: { with: /\A\S+@\S+\.\S+\z/ }
  validates :password, 
    format: { with: /\A[a-zA-Z0-9]+\z/ },
    length: { minimum: 8 }
  validates :phone_number, format: { with: /\A\d{10,11}\z/ }

  # アソシエーション
  has_many :charters
  has_many :sells
  has_many :purchases

  def self.guest
    find_or_create_by!(
      username: 'ゲスト',
      email: 'guest@example.com',
      phone_number: '09011223456',
      prefecture_address: '東京都',
      city_address: '中央区',
      house_number: '日本橋',
      ) do |user|
      user.password = SecureRandom.alphanumeric(8)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone_number, :prefecture_address, :city_address, :house_number])
  end
end

app/controllers/charters_controller.rb
class ChartersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_charter, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only:[:edit, :destroy]
  
  def index
    @charters = Charter.all
    @purchases = Purchase.all
  end
  def new
    @charter = Charter.new
  end

  def create
    @charter = Charter.create(charter_params)
    if @charter.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @sell = Sell.new
    @sells = @charter.sells.order(sell: :asc).order(created_at: :asc).first(1)
    @purchase = Purchase.new
  end
  
  def edit  
  end

  def update
    if @charter.update(charter_params)
      redirect_to  charter_path(@charter)
    else
      render :edit
    end
  end

  def destroy
    if @charter.destroy
      redirect_to root_path
    end
  end

  def search
    @charters = Charter.search(params[:keyword]) 
  end

  private
  def charter_params
    params.require(:charter).permit(:departure, :arrive, :size, :delivery_date, :buy_price, :prefecture_id, :city, :charter_address, :build_name, :tell_number).merge(user_id: current_user.id)
  end

  def set_charter
    @charter = Charter.find(params[:id])
  end

  def move_to_index
    @charter = Charter.find(params[:id])
    unless current_user.id == @charter.user_id
      redirect_to root_path
    end
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @charter = Charter.find(params[:charter_id])
    @sell = Sell.find(params[:charter_id])
    @user = User.find(params[:user_id])
    @purchase = Purchase.new
  end
  
  def create
    @charter = Charter.find(params[:charter_id])
    @purchase = Purchase.create(purchase_params)
    if @purchase.save
      redirect_to root_path
    end
  end
  private
  def purchase_params
    params.permit(:id).merge(user_id: current_user.id, charter_id: params[:charter_id])
  end
end

app/controllers/sells_controller.rb
class SellsController < ApplicationController  
  def create
    @sell = Sell.new(sell_params)
    if @sell.save
      redirect_to charter_path(@sell.charter)
    else
      @charter = @sell.charter
      @sells = @charter.sells
      redirect_to root_path
    end
  end

  def destroy
    @sell = Sell.find(params[:id])
    charter = Charter.find(params[:charter_id])
    if @sell.destroy
      redirect_to "/charters/#{charter.id}"
    end
  end

  private
  def sell_params
    params.require(:sell).permit(:sell).merge(user_id: current_user.id, charter_id: params[:charter_id])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @purchases = Purchase.all
    @charter = Charter.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charters_helper.rb
module ChartersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sells_helper.rb
module SellsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charters/_charters_bar.html.erb
<div id= '1' class='charter_bar'>
  <div class="charter_header">
    <div class="charter_header_name">チャーター便検索</div>
    <%= form_with(url: search_charters_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "到着場所で検索する", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
  </div>
</div>

app/views/charters/_charters_image.html.erb
<div class='charter-image'>
  <%= image_tag '1493950_l.jpg', class:'image'%>
  <div class='main-title'>Charter Trader</div>
  <div class='top-messages'>
    <div class='title_message_1'>チャーター便を</div>
    <div class='title_message_1'>お求めやすく</div>
  </div>
  <div class='buttons'>
    <div class='button scroll-btn'>
      <a href="#1">チャーター検索へ</a>
    </div>
    <div class='button order-btn'>
      <%= link_to 'チャーターをご要望の方', new_charter_path %>
    </div>
    <div class='button scroll-btn_2'>
      <a href="#2">Charter Traderとは</a>
    </div>
  </div>
</div>

app/views/charters/_charters_message.html.erb
<div id="2" class='charter-message'>
  <div class='top-contents'>
    <div class='main_message1'><p>引越しや大きい荷物を目的地に運ぶ際思っていたよりも値段が合わない場合がありませんか？</div>
    <div class='main_message1'>私たちがオークションでこれらの課題を解決します</div>
  </div>
</div>

app/views/charters/index.html.erb
<%= render "shared/header" %>

<div class='wrapper'>
  <%= render "charters_image" %>
  <%= render "charters_bar" %> 
  <%= render "charters_message"%>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CharterTrader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
    function initMap() {
      const target = document.getElementById('gmap');
      const address = document.getElementById('address').textContent;
      const geocoder = new google.maps.Geocoder();

      geocoder.geocode({ address: address }, function (results, status) {
        if (status === 'OK' && results[0]){
          const map =new google.maps.Map(target, {
            center: results[0].geometry.location,
            zoom: 16
          });
          const marker = new google.maps.Marker({
            position: results[0].geometry.location,
            map: map,
            animation: google.maps.Animation.DROP
          });
       
       
       }else{
         alert('失敗しました。理由: ' + status);
         return;
       }
      });
    }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>
  </body>
</html>

app/views/purchases/index.html.erb
<%= render "shared/header" %>
<div class="purchase-content">
<%# 購入内容の表示 %>
  <div class='purchase-details'>
    <div class='purchase-detail'>
      <%= "チャーター情報：#{@charter.departure}→#{@charter.arrive}" %>
    </div>
    <div class='purchase-detail'>
      <%= "チャーター先住所：#{@charter.prefecture.name}#{@charter.city}#{@charter.charter_address}#{@charter.build_name}" %>
    </div>
    <div class='purchase-detail'>
      <%= "電話番号：#{@charter.tell_number}" %>
    </div>
  </div>
  <div class='purchase-price'>
      <div class='purchase-detail detail-price'>
      <%= "チャーター購入価格：#{@sell.sell}円(税込)" %>
    </div>
  </div>
<%# 支払額の表示 %>
  <div class='purchase-user-detail'>
    <div class='purchase-detail'>
      <%= "チャーターを手配してくれるユーザー：#{@user.username}さん"%>
    </div>
    <div class='purchase-detail'>
      <%= "#{@user.username}さんの住所：#{@user.city_address}" %>
    </div>
    <div class='purchase-detail'>
      <%= "連絡先：#{@user.email}"%>
    </div>

  </div>
<%# チャーター便手配先業者の表示 %>
  <div class='purchase-user'>
  <p>上記の内容が本件のチャーター便の内容です</p>
  <p>上記の内容で間違いないでしょうか?</p>
  <p>間違いなければ下記の購入ボタンをクリックしてください</p>
<%# 購入ボタン %>
  <%= form_with(model: [@charter, @purchase],url: charter_purchases_path, id: 'charge-form', class: 'purchase-form-wrap',local: true) do |f| %>
    <%= f.submit "購入" ,class:"purchase-btn" %>
  <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
<footer>
  <ul class="copy-light">
  <li>©︎Charter Trader2020</li>
  <li>by Kazuki Narimatsu</li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class='header-left'>
    <%= link_to root_path do %>
    <%= image_tag "logo-image.png", class:'app-name'%>
    <% end %>
  </div>
  <div class="header-right">
    <ul class='sign_in_up_lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.username, user_path(current_user), class: "log-in-user" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, class: "log-out", method: :delete %></li>
      <% else %>
        <li><%= link_to '閲覧用', users_guest_sign_in_path, class: "log-in", method: :post %></li>
        <li><%= link_to 'ログイン', new_user_session_path, class: "log-in"%></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up"%></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="user-show">
  <div class="user-show-detail">
    <div class='user-title'>ユーザー名</div>
    <div class='user-name'><%= @user.username %>さん</div>
    <div class='user-title'>住所</div>
    <div class='user-name'><%= @user.city_address %></div>
    <div class='user-title'>連絡先</div>
    <div class='user-name'><%= @user.email %></div>
    <p></p>
  </div>
  <div class="user-show-purchase">
  <% if user_signed_in? %>
    <% if current_user.id == @user.id %>
      <div class='user-show-purchase-list'>
        <%= "#{current_user.username}さんのチャーター購入履歴"%>
      </div>
      <% @purchases.each do |purchase| %>
        <div class="purchase-lists">
          <% if current_user.id == purchase.user_id%>
          <%= link_to "#{purchase.charter.departure}→#{purchase.charter.arrive}", charter_path(purchase.charter) %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>

  </div>
</div>
<%= render "shared/footer" %>